groups:
    type:       rest
    resource:   AppBundle\Controller\Api\GroupController

emoticons:
    type:       rest
    resource:   AppBundle\Controller\Api\EmoticonController

me:
    type:       rest
    resource:   AppBundle\Controller\Api\MeController

chats:
    type:       rest
    resource:   "chats_routes.yml"

users:
    type:       rest
    resource:   "users_routes.yml"