<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversationIntervalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationIntervalRepository extends EntityRepository
{
}
