<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmoticonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmoticonRepository extends EntityRepository
{
    public function findAllOrdered($orderBy = "sortOrder", $orderDirection = "ASC")
    {
        return $this->findBy([], [$orderBy => $orderDirection]);
    }

    public function findSmiley()
    {
        return $this->findOneBy(['symbol' => ':-)']);
    }
}
