<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageComplaintRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MessageComplaintRepository extends EntityRepository
{
    public function getOpenComplaintsCount()
    {
        $res = $this->createQueryBuilder('mc')
            ->select('COUNT(mc) cnt')
            ->where('mc.status = :open_status')
            ->setParameter('open_status', MessageComplaint::STATUS_OPEN)
            ->getQuery()->execute();

        return (int) $res[0]['cnt'];
    }
}
